### ISSUE TITLE
Automate regenerating vendored licenses?

### ISSUE THREAD

**Issue by mxr** [pre-commit/identify#175]
Just some random thoughts, can we automate regenerating vendored licenses? Could pre-commit.ci invoke this once every X days; does it need to be a hook for that? How should version numbers change when licenses are updated? etc...

**Comment by asottile** [comment]
yeah it would have to be a hook and with a version some how, I don't think abusing pre-commit.ci to do this is a good idea

I'm also not really sure that we need to update it often, nobody has asked about it in a while and the only consumer I know of is `setup-cfg-fmt` which has an even-more-restrictive set of licenses it supports (due to pypi)

probably not worth over-engineering this

**Comment by mxr** [comment]
Makes sense, thanks for the context
